// <auto-generated />
namespace Online_Game_store.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addedContacts : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedContacts));
        
        string IMigrationMetadata.Id
        {
            get { return "202012281655445_addedContacts"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
