// <auto-generated />
namespace Online_Game_store.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addedGames : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedGames));
        
        string IMigrationMetadata.Id
        {
            get { return "202012281430438_addedGames"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
